# /etc/fail2ban/jail.d/secure-login.conf
[DEFAULT]
bantime = 1h
findtime = 10m
maxretry = 6
backend = systemd
banaction = ufw

[sshd]
enabled = true
port = 2222
logpath = %(sshd_log)s
maxretry = 5

[nginx-http-auth]
enabled = true
port = http,https
logpath = /var/log/nginx/error.log

[nginx-botsearch]
enabled = true
port = http,https
logpath = /var/log/nginx/access.log
maxretry = 3

[secure-login-nginx-429]
enabled = true
port = http,https
filter = secure-login-nginx-429
logpath = /var/log/nginx/access.log
findtime = 5m
maxretry = 20
bantime = 30m
